### PR TITLE
Add other key type examples

### PR DESCRIPTION
**Pull request by OR13**
Additional source code / tests available here: https://github.com/transmute-industries/did-key.js

### CODE REVIEW

**Review by dmitrizagidulin — APPROVED** [review]
👍  thanks @OR13 !

**Review by dlongley — APPROVED** [review]
I didn't run any code or do anything to "test the test vectors" here ... so presuming it all matches up with the appropriate multicodec stuff, it seems ok. We haven't said whether or not an x25519 key should expand to more than just `keyAgreement` -- whereby we choose a particular sign for the ed25519 equivalent (this is what Signal does), but we could proceed without that for now, I suppose.

**Comment by OR13** [comment]
@dlongley @dmitrizagidulin  I could use a sanity check on the multicodec stuff, you can manually obtain additional test vectors for all key types here https://key.did.ai/

assuming that what I wrote is correct :)

**Comment by OR13** [comment]
merging

**Pull request merged**
